name: socially
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.4

  # Service locator
  get_it: ^7.2.0
  # Bloc for state management
  flutter_bloc: ^8.0.1
  # Value equality
  equatable: ^2.0.3
  dartz: ^0.10.1

  # Local database
  hive: ^2.1.0
  hive_generator: ^2.0.1
  # Path provider
  path_provider: ^2.0.9
  connectivity_plus: ^5.0.2
  dio: ^4.0.4
  provider: ^6.0.2
  fluttertoast: ^8.2.5
  http: ^0.13.6
  bloc_test: ^9.1.7
  flutter_form_builder: ^7.8.0
  flutter_screenutil: ^5.9.1
  flutter_phoenix: ^1.1.1
  smartrefresh: ^0.0.2
  pull_to_refresh: ^2.0.0
  change_app_package_name: ^1.1.0
  flutter_native_splash: ^2.4.0
  flutter_svg:
  persistent_bottom_nav_bar:
  cached_network_image:
  shimmer:
#flutter_native_splash:
#  color: "#05101C"
#  android: true
#  ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Mocking library
  mockito: ^5.1.0


  # Build runner
  build_runner: ^2.1.10



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/db.json
    - assets/icons/